services:
  odoo18_web:
    build: .
    depends_on:
      - odoo18_postgres
    ports:
      - "8071:8071"
    volumes:
      - odoo18_volumen:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=odoo18_postgres
      - USER=odoo
      - PASSWORD=odoo

  odoo18_postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo18_volumen_db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com  # Set default admin email
      - PGADMIN_DEFAULT_PASSWORD=admin  # Set default admin password
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persistent storage for pgAdmin
volumes:
  odoo18_volumen:
  odoo18_volumen_db:
  pgadmin_data:  # Volume for pgAdmin to store data